### ISSUE TITLE
Cover Icon inconsistency 

### ISSUE THREAD

**Issue by dizzi90** [jgibbon/Talefish#14]
See pic

**Comment by dizzi90** [comment]
![screenshot_20181121_002](https://user-images.githubusercontent.com/3081351/48864201-208ca680-edcc-11e8-8cc7-442128289b73.png)
![screenshot_20181121_001](https://user-images.githubusercontent.com/3081351/48864204-23879700-edcc-11e8-9f7c-9752cc049662.png)

**Comment by jgibbon** [comment]
Thanks for finding and raising this!
The correct icon will be shown in the next release.

cheers!
