### ISSUE TITLE
Playback speed range

### ISSUE THREAD

**Issue by leanderhoermann** [jgibbon/Talefish#16]
Great app. Please increase playback speed range e.g. from 50% to at least 200%.

**Comment by jgibbon** [comment]
I'll just copy what I [responded](https://openrepos.net/comment/26476#comment-26476) to an enquiry on openrepos for this:

 > […] because I have no method of pitch correction, this will produce really low or high pitched output. I have yet to discover audiobooks where even 80 (really bassy) or 120 (squeaky like a dog toy) is bearable. Are you **sure** you have a real use case for that?

Another reason I hesitate is that setting the desired value may become a bit harder with a bigger range.

If you have such a use case, I am really, really interested in hearing more about it – I may even reconsider. ;)

cheers

**Comment by leanderhoermann** [comment]
Thanks for your quick response. You are right, without pitch correction
it is not really reasonable to modify the speed in a wider range.
With a pitch correction, the use case would be to hear audio books
faster (depending on the audio book of course).

Cheers

Von: jgibbon <notifications@github.com>
An:jgibbon/Talefish <Talefish@noreply.github.com>
CC:leanderhoermann <leander.hoermann@lcm.at>, Author
<author@noreply.github.com>
Datum: 08.01.2019 15:11
Betreff: Re: [jgibbon/Talefish] Playback speed range (#16)
I'll just copy what I responded
( https://openrepos.net/comment/26476#comment-26476)  to an enquiry on
openrepos for this:
[…] because I have no method of pitch correction, this will produce
really low or high pitched output. I have yet to discover audiobooks
where even 80 (really bassy) or 120 (squeaky like a dog toy) is
bearable. Are you sure you have a real use case for that?
Another reason I hesitate is that setting the desired value may become
a bit harder with a bigger range.
If you have such a use case, I am really, really interested in hearing
more about it – I may even reconsider. ;)
cheers
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
( https://github.com/jgibbon/Talefish/issues/16#issuecomment-452311244)
, or mute the thread
(

**Comment by jgibbon** [comment]
Agreed, pitch correction would be really good. 
I have searched long and hard for lightweight solutions to integrate with Qt Audio but have found none that was even remotely feasible, sadly.
