### ISSUE TITLE
If Talefish doesn't find the audio file it played last, it doesn't start

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#17]
I sync my podcasts between phone and desktop. When I've finished a podcast I delete it from the phone and/or PC. If Talefish gets started and doesn't find the last played audio file it doesn't start anymore. It used to work before.

My workaround: Login to shell, start Talefish on the console, then it prints the missing file, I then recreate that file (or a symbolic link to any audio file) and restart Talefish. It's a pain and I need a PC for that, so I can't do that while commuting.

**Comment by jgibbon** [comment]
Oh dear. 
Thank you for finding this! That's a pretty hardcore workaround you got there.
The problem should be fixed with the fresh 0.1-2 release on openrepos. If it isn't, please feel free to reopen this issue.
cheers!

**Comment by dimpflmoser** [comment]
Just tested it and it seems to work. Thanks!

**Comment by jgibbon** [comment]
Thank you for testing it!
