### ISSUE TITLE
featureRequest: 3 button cover action

### ISSUE THREAD

**Issue by carlosgonz0** [jgibbon/Talefish#19]
rewind   play/stop  forward   and clean up from Talefish-settings
recicling features:https://github.com/equeim/unplayer/blob/b41150b64d1af0e046dbec9f6991ca5574d2aea9/qml/components/Cover.qml

**Comment by jgibbon** [comment]
Ok

**Comment by carlosgonz0** [comment]
yes, yes, yes \ 0 /
thnks
