### ISSUE TITLE
File dialog: Comfortable handling of deleted "previously opened folder"

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#20]
When I delete a directory that was played before by Talefish, thanks to #17 it does not crash anymore, however if you open a new directory it will start from / (root). It would be nice if you could define a default directory in options, such as /media/sdcard/Podcasts, that will be opened if Talefish cannot find its current / previous directory.

**Comment by jgibbon** [comment]
Thanks for reporting this! While it _should_ start from /home/nemo (not /) when a directory isn't found, I agree that this can be improved.
But in my opinion this shouldn't be done with another option, but rather using better default behaviour. The best I can think of is actually still using the last directory, but if it's not available, to try it's parent(s) until something is found. 
I am going to implement that for the next release (which will be on openrepos in the next 1-2 weeks or so) and hope that it still fits your needs. :)

**Comment by dimpflmoser** [comment]
Actually as far as I remember it used to fall back to /home/nemo/ until some recent update, but this has changed some time ago. Since I moved my content to sdcard the solution you suggested would suit my needs perfectly.
Don't be pushed, since you have fixed #17 I'm pretty happy with Talefish, it doesn't matter how long it takes for you to pick up on this issue .

**Comment by jgibbon** [comment]
Hi @dimpflmoser – since file handling underwent a complete rewrite in the latest release, I think/hope we can finally close this one. Now you can just add folders as favourites to quickly go there again. What do you think?
cheers!

**Comment by dimpflmoser** [comment]
Oh yes, of course, I think it was already alright before the rewrite.
Have not yet fully familiarised with the new UI but up to now I haven't found any issues.
Thanks
