### ISSUE TITLE
Headset Buttons: double/triple click

### ISSUE THREAD

**Issue by jgibbon** [jgibbon/Talefish#21]
User suggestion: Add options to skip to next /previous track When I press the only button on my headset（such as Sony's）.Such as press twice to skip to next track quickly and press  3 times quickly to skip to previous  track
edit: And control volume too(turn up /down or mute )by pressing only button double /triple quickly .

**Comment by dimpflmoser** [comment]
Oh yes I would love such a feature.
My (Bluetooth) headset (LG) does have 3 Buttons (forward/rewind/start-stop). My start-stop button works as expected, the forward and rewind button jump to the next / previous track. However I would love to jump back by several seconds if miss something. This is normally done with short and long press, however my headset does not seem to support long presses. So double or tripple press would give a nice workaround

**Comment by jgibbon** [comment]
@dimpflmoser The long press setting is meant for headsets with only a "call/hangup button".
You can set a skip mode for all external commands (including app cover/lock screen and media keys – which is most likely what your headphones trigger) globally, though, if that helps you:
[mode setting screenshot](https://i.imgur.com/EVJ6Acg.jpg)

**Comment by dimpflmoser** [comment]
Thanks for the hint, actually I would not like to give up the jump to next/previous track for skip/rewind. So this is why a double click interaction would be helpful

**Comment by jgibbon** [comment]
Okay, thanks for clarification – you got a point there. 
As these are handled exactly the same as the other external commands (the call/hangup button is a separate thing, so it would be a bit easier to do there and was the scope of the initial suggestion) it could interfere a bit with those or at least reduce percepted performance in some cases.
 
I promise to _at least_ think some more about a sane implementation "at some point in the far future", which I neglected for the current "big" release, I must confess. :)

Cheers!

**Comment by jgibbon** [comment]
Sadly, the custom button click functionality won't work anymore from SFOS 4.2 upwards. SFOS now handles the MediaKeys itself and things break as soon as the permission is requested.
