### ISSUE TITLE
FeatureRequest: LDAC

### ISSUE THREAD

**Issue by carlosgonz0** [jgibbon/Talefish#25]
Hi @jgibbon 
 I was thinking if there is the possibility of routing the audio HD of Talefish for a bluetooth output like LDAC.
https://www.sony.net/Products/LDAC/
https://android.googlesource.com/platform/external/libldac
https://github.com/EHfive/pulseaudio-modules-bt
![pulseaudu](https://user-images.githubusercontent.com/45316884/70220354-6f298c00-1714-11ea-90ce-a045a704bb48.png)

**Comment by jgibbon** [comment]
Hi @GNUuser,
I'm sorry, but this is way out of scope for a "simple" user-space application like Talefish. 
It's part of the audio/bt backend of the operating system. 
Also, from what I've gathered, LDAC requires license payments, so I guess not even Jolla will touch this topic soon. 
You're obviously already more informed about some of these topics than I am, but here are related TJC pages for reference: https://together.jolla.com/questions/query:LDAC/

thanks for bringing it up though!
