### ISSUE TITLE
FeatureRequest: HD like Icon

### ISSUE THREAD

**Issue by carlosgonz0** [jgibbon/Talefish#26]
HI @jgibbon 
I would like to see an icon with HD symbology in Talefish to describe a high definition audio file is being played like Flac 16bit/24bit. #25

**Comment by jgibbon** [comment]
Hi @GNUuser,
this is an interesting idea, though it's not really relevant to the core usage scenario for Talefish, which is mostly consuming voice/story centric audio. 

That put aside, 
- I can not think about either a good way to represent nor to even categorize the different file types, bitrates, sample rates, and what ever else comes to mind there. Also, most recognizable icons in that area are copyrighted to my knowledge.
- With the (in some cases) already pretty cramped interface (header, cassette progress, track meta data, track progress bar, playlist progress bar, buttons, cover), I can't even think of a sensible place for such an icon, to be honest – especially on smaller devices.

I'm leaving this issue open for now, perhaps you can convince me with a good way to solve those problems. But please try not to be disappointed should I disagree. :)

Thanks for bringing it up!
