### ISSUE TITLE
pitch compensation for different playback rates

### ISSUE THREAD

**Issue by thigg** [jgibbon/Talefish#30]
in the future (with qt5.12) pitch compensation could be done with [this](https://doc.qt.io/qt-5/qml-qtmultimedia-mediaplayer.html#source-prop) using a gstreamer pipeline which utilizes `scaletempo`

**Comment by jgibbon** [comment]
Thanks for investigating this. 
I don't think SailfishOS will get a Qt-Update soon, so I'll close this in the meantime. 
It may be reopened to check the feasibility if the situation changes.
cheers!
