### ISSUE TITLE
Progress randomly (?) lost

### ISSUE THREAD

**Issue by ichthyosaurus** [jgibbon/Talefish#31]
Talefish (0.5-5) seems to lose the current directory's progress after some time.

Steps:
- start Tailfish, open a directory
- listen for a while
- close the app
- when opened a short time later, the progress is still there
- when opened a long while (a few days?) later, the progress is lost
- it also seems to happen after a reboot

I'm not quite sure when exactly the progress is lost. In the database, "currentPlaylist" does not change but "playlistProgress" is an empty object...

Maybe relevant: my audio books are stored on the SD card, and the path has umlauts in it.

I have no idea how to properly debug this :/.

**Comment by jgibbon** [comment]
Hi,
thanks for reporting this. 
It would be great if you could help me investigate this further:
- Just to be sure we're talking about the same thing: When you open Talefish and the progress is lost, the right files are still opened but at the beginning? Or does it start without any files opened?
- It is normal that playlistProgress gets purged after a while, this should only affect re-opening directories, not the currently played tracks. It is configurable in the options.
- Can you check if somehow the path to your sd card has changed?
- Do you have the "save progress periodically" option enabled? If you don't, progress will only be saved when the application _cleanly_ exits. Getting stopped by the memory management (more transparent app cover) does not count as "clean".

cheers!

**Comment by ichthyosaurus** [comment]
> the right files are still opened but at the beginning

exactly; it starts at the beginning of the playlist

> It is normal that playlistProgress gets purged after a while, this should only affect re-opening directories, not the currently played tracks. It is configurable in the options.

I configured it to "never" forget the progress, and in the database "keepUnopenedDirectoryProgressDays" is "9999". I also tried resetting the config but that didn't help either.

> Can you check if somehow the path to your sd card has changed?

I don't think so... Also, the last directory is remembered correctly. Well, and the playlist always is still there and usable. It's not that the files are gone.

> Do you have the "save progress periodically" option enabled?

yes


Hope this can help you!

**Comment by jgibbon** [comment]
As you might've noticed from this issue being closed by a commit yesterday night, I've found quite a few "possible" problems (that for some reason didn't materialize for most people including me) I was able to address or will continue to fix in the next weeks – some things will have to be changed before anyone else should try it. Then I'll have to test it in real world conditions for a while. If you'd like to test that version, as well, be sure to hit me up.

Alternatively, should this problem persist after the following release (will take a while), please let me know!

**Comment by ichthyosaurus** [comment]
This is great news, thank you! I'll sure test it when you think it's ready :).

**Comment by jgibbon** [comment]
If you feel adventurous, you can try an automated test build (sfos 3.4 target) done by github containing these and many more changes even before I had a few days to test: https://github.com/jgibbon/Talefish/releases/tag/release-0.5-6

You may want to backup your ~/.local/share/harbour-talefish directory if you don't want to lose settings and the last directory etc. But it should (tm) not happen. Still, I changed a lot, please let me know if everything works for you. ;)

cheers!

**Comment by ichthyosaurus** [comment]
Sorry I forgot to answer! I tested it and everything seems to work perfectly fine! Thanks for fixing this :)

**Comment by jgibbon** [comment]
Awesome, thank you very much for checking it out and sorry for taking so long – I busied myself helping out with Fernschreiber.
Another tester and me only had some minor gripes with an unrelated change, so the next "public" release is almost on the horizon.

cheers!

**Comment by ichthyosaurus** [comment]
That's great news :)
