### ISSUE TITLE
Issue with SFOS 3.4.0.24

### ISSUE THREAD

**Issue by dimpflmoser** [jgibbon/Talefish#32]
After updating SFOS from.3.4.0.22 to 3.4.0.24 Talefish does not play media files any more. They play well in FileCat and Unplayer.

When you select a file an wipe right you hear a tick in the speaker/headset as it happens with all other players.
It seems to open the file but just halts.

Is that just me or does this happen to others as well?

**Comment by jgibbon** [comment]
I wasn't able to reproduce this error with my usual Test Files on 3.4.0.24. AFAIK, Talefish uses the same playback mechanism (QML Audio) under the hood as FileCat does, which makes this even more weird.
What kind of files did you try?

**Comment by dimpflmoser** [comment]
After reboot of the phone it works again.
Never had an issue with Talefish that required a reboot. Sorry for the fuss.
