### ISSUE TITLE
playback speed not always set

### ISSUE THREAD

**Issue by thigg** [jgibbon/Talefish#33]
1. Set playback speed != 1
2. audio plays faster.
3. wait until track changes
IS: after track change, playback speed jumps back to 1
SHOULD: keep the set playback speed

and 

1. Have playback speed != 1
2. Close app
3. start app
4. start audio
IS: playback speed back to 1
SHOULD: keep the set playback speed

Background is that the QtMediaPlayer of Sailfish gets pitch compensation when playback speed is changed:
https://forum.sailfishos.org/t/no-pitch-compensation-when-playing-audio-with-playbackrate-1/

**Comment by jgibbon** [comment]
Thank you for investing your time to not only find and fix an issue here but to enhance that behaviour [for (almost) all applications](https://forum.sailfishos.org/t/no-pitch-compensation-when-playing-audio-with-playbackrate-1/1369/15)!
Very much appreciated!

**Comment by jgibbon** [comment]
The current mer-5.6 branch of qtmultimedia including your patch (and apparently another small fix for it) is really great. Finally, the speed setting in Talefish makes sense!

I hope to find the time to fix this issue, at least for a whole lot of different use cases (the bug materializes a bit differently depending on when and how a file is loaded) next weekend. Release may take a bit longer.

cheers!

**Comment by thigg** [comment]
Keep me updated, podqast has the same problems. But I gonna do some refactorings before I fix this.

**Comment by thigg** [comment]
https://forum.sailfishos.org/t/qml-mediaplayer-playbackrate-not-wired-up-correctly/6165

opened bug report

**Comment by jgibbon** [comment]
Workaround is working reasonably well, hopefully for all use cases, released with 0.7-1 (on openrepos for now).
Thanks for all your work!
