### ISSUE TITLE
Add 64bit builds

### ISSUE THREAD

**Issue by thigg** [jgibbon/Talefish#35]
It looks like the Xperia 10 II gets a 64bit build of SFOS. Thus it would make sense to create arm 64bit builds already.

**Comment by jgibbon** [comment]
At least in the jolla store, a 64bit build was already added with the latest release (though I am unable to test that). 
I'll start adding them to openrepos with the next one that – thanks to you – may come really soon.

This issue will stay open as a reminder until then, though. Thanks!

**Comment by jgibbon** [comment]
Latest release on openrepos now has a 64 bit build. Hopefully it works. ;)

Again, thanks for the reminder!
