### ISSUE TITLE
Resource not found when moving to next track automatically or via cover action

### ISSUE THREAD

**Issue by topiasv** [jgibbon/Talefish#41]
When you hit the end of a file, Talefish fails to move onto the next track automatically and only gives you a [Resource not found]. Same issue occurs on cover action skip buttons. The issue does not however occur when you do the side swipes within the app. I'm running Sailfish 4.5 on Xperia 10 II. Tried to play tracks of different formats (m4b and mp3) as well as from different directories (sdcard and home) for good measure. If you need any more information, I can do some more debugging.

**Comment by topiasv** [comment]
I tried to reproduce this bug again but now it seems like it's gone. Not sure why but it stopped occurring after I closed the app and relaunched once from terminal so I could read the logs. I will keep an eye on it if reoccurs but seems like this is an elusive one.

**Comment by jgibbon** [comment]
Thanks for taking the time to report, nevertheless.
If you keep an eye open for this one, here's some minimal context: The "Resource not found" error gets shown when the (mostly standard qml) Player-Component fails to find/open the current file. I've only had that with huge files (>2gb) that the system can't handle at all or obviously when I moved a file or folder after opening.

From first glance it seems like a "hiccup" somewhere in the standard Audio Components, but that's just a wild guess.
Did you still see some cover art? (Provided there even was an embedded image or image file in the folder…)

cheers!

**Comment by topiasv** [comment]
Whenever the error message was shown, there was nothing but the text label. No cover art was shown so it seemed to have completely dropped the ball. The files weren't that big nor had I moved them so those shouldn't have been the cause. Can't think of any other anomalies that could have been the cause. Still not sure what happened but I'll keep an eye out nevertheless.
