### ISSUE TITLE
[ WISH LIST ]

### ISSUE THREAD

**Issue by ghost** [jgibbon/Talefish#6]
- Support OPUS audio format
- Support NEXT TRACK on multitask
- =  )

**Comment by jgibbon** [comment]
I didn't realise that .opus is now supported in the backend. Nice.

Thanks for the suggestions. I especially like the third one. :)

**Comment by jgibbon** [comment]
@Caballlero Have you set up the SailfishOS SDK? 
If so, could you test the changes and tell me if it it works for you this way?

The secondary app cover button is set to "skip backwards" by default, because for myself it's more common to be distracted and miss something in an audio book than to skip stuff.

**Comment by ghost** [comment]
Jajaja you like the third one
I am ok - on  is set to "skip backwards"
Yes  i have SailfishOS SDK already
WHAT DO WANT @jgibbon ?

**Comment by jgibbon** [comment]
I really don't _want_ anything, just thought you might like to test the changes:
 - open the project with the last two commits (where I've added the features you requested) in SDK
 - build / deploy
 - check if it works, especially loading your .opus files… because I only tested with an example I downloaded from the opus website. 

If you don't want to, I'll try to encode some files on the weekend to test with.

**Comment by ghost** [comment]
OKAY.  
I build talefish with the new sailfishSDK [ 1701 ]
- I tested .opus file > >>>>>>>>>>>>>>>> PASS
- I tested  secondary app-cover button >> PASS
- I tested english layout >>>>>>>>>>>>>> PASS
Can you add in the next release talefish version number in about page?

TALEFISH now is HIGHLY CUSTOMIZABLE !!! NICE

**Comment by jgibbon** [comment]
Thanks for testing!

If you mean releasing a new build on openrepos, I'll update the changes file and build number and prepare a new build soon. I'll close this issue after that.

(For me, SDK 1701 did not work well (ignored translation changes and the new features were unusable), so I'm still using the stable one.)

Thanks, again, both were good Ideas!

**Comment by ghost** [comment]
I want to tell that when i build talefish ,then intalled in my phone i dont get spanish translation that why i told you that english layout is perfect, because I did not get the Spanish translation

**Comment by jgibbon** [comment]
Ok, maybe the SDK 1701 does not work correctly on your machine, as well. (There are some errors about the translation files when building…)

**Comment by ghost** [comment]
Updating '/home/mersdk/share/Talefish/translations/Talefish-pl.qm'...
    Generated 54 translation(s) (54 finished and 0 unfinished)
    Ignored 35 untranslated source text(s)
install -m 644 -p /home/mersdk/share/Talefish/"/home/mersdk/share/Talefish/translations/Talefish-en.qm" /home/deploy/installroot/usr/share/Talefish/translations/
install: cannot stat `/home/mersdk/share/Talefish//home/mersdk/share/Talefish/translations/Talefish-en.qm': No such file or directory
make: [install_qm] Error 1 (ignored)
install -m 644 -p /home/mersdk/share/Talefish/"/home/mersdk/share/Talefish/translations/Talefish-de.qm" /home/deploy/installroot/usr/share/Talefish/translations/
install: cannot stat `/home/mersdk/share/Talefish//home/mersdk/share/Talefish/translations/Talefish-de.qm': No such file or directory
make: [install_qm] Error 1 (ignored)
install -m 644 -p /home/mersdk/share/Talefish/"/home/mersdk/share/Talefish/translations/Talefish-sv.qm" /home/deploy/installroot/usr/share/Talefish/translations/
install: cannot stat `/home/mersdk/share/Talefish//home/mersdk/share/Talefish/translations/Talefish-sv.qm': No such file or directory
make: [install_qm] Error 1 (ignored)
install -m 644 -p /home/mersdk/share/Talefish/"/home/mersdk/share/Talefish/translations/Talefish-es.qm" /home/deploy/installroot/usr/share/Talefish/translations/
install: cannot stat `/home/mersdk/share/Talefish//home/mersdk/share/Talefish/translations/Talefish-es.qm': No such file or directory
make: [install_qm] Error 1 (ignored)
install -m 644 -p /home/mersdk/share/Talefish/"/home/mersdk/share/Talefish/translations/Talefish-ru.qm" /home/deploy/installroot/usr/share/Talefish/translations/
install: cannot stat `/home/mersdk/share/Talefish//home/mersdk/share/Talefish/translations/Talefish-ru.qm': No such file or directory
make: [install_qm] Error 1 (ignored)
install -m 644 -p /home/mersdk/share/Talefish/"/home/mersdk/share/Talefish/translations/Talefish-pl.qm" /home/deploy/installroot/usr/share/Talefish/translations/
install: cannot stat `/home/mersdk/share/Talefish//home/mersdk/share/Talefish/translations/Talefish-pl.qm': No such file or directory
make: [install_qm] Error 1 (ignored)
cp -f -R /home/mersdk/share/Talefish/qml /home/deploy/installroot/usr/share/Talefish/
install -m 755 -p Talefish /home/deploy/installroot/usr/bin/Talefish

**Comment by ghost** [comment]
it something about [install_qm] @jgibbon ?

**Comment by jgibbon** [comment]
Yes, those. 
That's why I downgraded to "stable" SDK 1611 again, which is not broken.

**Comment by ghost** [comment]
any idea to resolve it ? you are more advanced than me

what operating system you are using in your machine? just to know

**Comment by jgibbon** [comment]
I'm using Linux.

I haven't had the time to investigate.
 - perhaps the early access sdk preview release is just buggy.
 - perhaps I just need to change something in the project settings. But I haven't seen anything in release notes or anywhere else mentioning it and won't waste my free time on "hunting ghosts".

The normal SDK 1611 is recommended by jolla for releasing Software and it works, so I'm using that for production stuff.

But I think it's a bit off-topic in this issue :)

**Comment by ghost** [comment]
ok

**Comment by jgibbon** [comment]
Features implemented and released in 0.0-8

**Comment by ghost** [comment]
Vielen Dank, Sie sind gute Person
